spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users-microservice
    username: root
    password: 211772809
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Opciones: none, validate, update, create, create-drop
    show-sql: true # Muestra las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public_key.pem
server:
  port : 8085
 
