spring:
  cloud:
    gateway:
      routes:
        - id: servicio_login
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/mx
            - Method=POST,GET
        - id: servicio_usuarios
          uri: http://localhost:8086
          predicates:
            - Path=/get/all
            - Method=GET
                 
        - id: servicio_create_usuario
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/mx/create
            - Method=POST
        - id: servicio_tasks
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/mx/tasks
            - Method=POST,GET,PUT
        - id: servicio_tasks_create
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/mx/tasks/create/new
            - Method=POST
        - id: servicio_tasks_gettasks
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/mx/tasks/list/get
            - Method=GET
        - id: servicio_tasks_updatetask
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/mx/tasks/change-status
            - Method=Put
        